site_name: L01D's Obsidian MkDocs

theme:
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # - attr_list
  # - pymdownx.arithmatex
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  # - pymdownx.tasklist:
  #     custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - admonition
  - toc:
      permalink: true

plugins:
  - search
  - pub-obsidian
    obsidian_dir: .obsidian
    templates_dir: _templates

    callouts:
      enabled: true
      indentation: spaces
    callouts:
      enabled: true
      indentation: spaces
    links:
      wikilinks_enabled: true
      img_lazy: true
    vega:
      enabled: true
      vega_schema: https://vega.github.io/schema/vega/v5.json
      vega_lite_schema: https://vega.github.io/schema/vega-lite/v5.json
